version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: .docker/php/Dockerfile
        container_name: laravel-app
        volumes:
            - .:/var/www
        depends_on:
            - mysql

    webserver:
        image: nginx:stable-alpine
        container_name: nginx
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
            - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app

    mysql:
        image: mysql:5.7
        container_name: mysql
        restart: always
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: laraveluser
            MYSQL_PASSWORD: secret
        volumes:
            - dbdata:/var/lib/mysql

volumes:
    dbdata:
